stages:
  load_save:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/dog
      - data/cat

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=config/config.yaml
    deps:
      - src/stage_02_prepare_base_model.py
      - src/utils/all_utils.py
      - src/utils/model.py
      - params.yaml
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - CLASSES
    outs:
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/base_model/VGG16_base_model.h5