stages:
  load_save:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml 
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data/dog
      - data/cat

  prepare_base_model:
    cmd: python src/stage_02_prepare_base_model.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare_base_model.py
      - src/utils/all_utils.py
      - src/utils/model.py
      - params.yaml
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - CLASSES
    outs:
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/base_model/VGG16_base_model.h5

  prepare_callbacks:
    cmd: python src/stage_03_prepare_callbacks.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_prepare_callbacks.py
      - src/utils/all_utils.py
      - src/utils/create_callbacks.py
      - params.yaml
      - config/config.yaml
    outs:
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb

  train:
    cmd: python src/stage_04_train.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_04_train.py
      - src/utils/all_utils.py
      - src/utils/model.py
      - src/utils/create_callbacks.py
      - src/utils/data_management.py
      - config/config.yaml
      - data
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/callbacks/checkpoint_cb.cb
      - artifacts/callbacks/tensorboard_cb.cb
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
    outs:
      - artifacts/model
