artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CALLBACKS_DIR: callbacks
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_root_dir
  CHECKPOINTS_DIR: chekpoints
  DATA_DIR: data
  LOG_DIR: logs

source_download_dirs:
  - ../outside_data/dog
  - ../outside_data/cat


local_data_dirs:
  - data/dog
  - data/cat